# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set environment variables to avoid writing pyc files and to ensure Python buffers output to the terminal
ENV PYTHONUNBUFFERED 1

# Set the working directory to /app in the container
WORKDIR /app

# Install system dependencies required for Django and Gunicorn
RUN apt-get update && apt-get install -y \
    build-essential \
    libmariadb-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /app
COPY . /app/

# Upgrade pip to ensure we're using the latest version
RUN pip install --upgrade pip

# Install required Python packages (from requirements.txt)
RUN pip install -r requirements.txt

# Collect static files (optional, but recommended for production environments)
# RUN python manage.py collectstatic --noinput

# Expose the port that the app will run on
EXPOSE 8000

# Command to run Gunicorn with Django
CMD ["gunicorn", "url_shortner_backend.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
